#ifndef YH_PLATFORM_GL_LINUX_H_
#define YH_PLATFORM_GL_LINUX_H_

#include "../PlatformConfig.h"
#if YH_TARGET_PLATFORM == YH_PLATFORM_LINUX

#include "GL/glew.h"

#define YH_GL_DEPTH24_STENCIL8      GL_DEPTH24_STENCIL8

#endif // YH_TARGET_PLATFORM == YH_PLATFORM_LINUX

#endif // YH_PLATFORM_GL_LINUX_H_
